[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
[".rio/themes/lucario.toml"]
    type = "file"
    url = "https://github.com/raphamorim/lucario/raw/main/rio/lucario.toml"
    refreshPeriod = "168h"