performance = "High"
height = 438
width = 662

[style]
font = "Hack Nerd Font"
font-size = 16
theme = "lucario"

[advanced]
tab-character-active = '●'
tab-character-inactive = '■'
disable-renderer-when-unfocused = false

[developer]
enable-fps-counter = false
log-level = 'OFF'+
